/* Generated By:JJTree&JavaCC: Do not edit this line. CSSParserImplConstants.java */
package com.sun.stylesheet.css.parser;

public interface CSSParserImplConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int DECIMAL_LITERAL = 6;
  int INTEGER_LITERAL = 7;
  int NEW = 8;
  int IMPORTANT = 9;
  int OVER = 10;
  int PROGRAMMATIC_PSEUDOCLASS = 11;
  int COLON = 12;
  int SEMICOLON = 13;
  int GT = 14;
  int PLUS = 15;
  int LEFT_BRACE = 16;
  int RIGHT_BRACE = 17;
  int DOT = 18;
  int COMMA = 19;
  int PERCENT = 20;
  int STRING = 21;
  int HEXCOLOR = 22;
  int HEXDIGIT = 23;
  int EXCL = 24;
  int LEFT_PAREN = 25;
  int RIGHT_PAREN = 26;
  int LINEAR = 27;
  int RADIAL = 28;
  int FOCUS = 29;
  int STOPS = 30;
  int TO = 31;
  int REPEAT = 32;
  int REFLECT = 33;
  int PERCENTAGE = 34;
  int LENGTH = 35;
  int TIME = 36;
  int DEFAULT_INTERPOLATION = 37;
  int EASE_IN = 38;
  int EASE_OUT = 39;
  int EASE_IN_OUT = 40;
  int IDENTIFIER = 41;
  int LETTER = 42;
  int DIGIT = 43;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 5>",
    "<DECIMAL_LITERAL>",
    "<INTEGER_LITERAL>",
    "\"new\"",
    "\"important\"",
    "\"over\"",
    "<PROGRAMMATIC_PSEUDOCLASS>",
    "\":\"",
    "\";\"",
    "\">\"",
    "\"+\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "\"%\"",
    "<STRING>",
    "<HEXCOLOR>",
    "<HEXDIGIT>",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"linear\"",
    "\"radial\"",
    "\"focus\"",
    "\"stops\"",
    "\"to\"",
    "\"repeat\"",
    "\"reflect\"",
    "<PERCENTAGE>",
    "<LENGTH>",
    "<TIME>",
    "\"default\"",
    "\"ease-in\"",
    "\"ease-out\"",
    "\"ease-in-out\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"*\"",
    "\"#\"",
  };

}
