/* Generated By:JJTree: Do not edit this line. ../../build/parser/com/sun/stylesheet/css/parser/CSSParserImplTreeConstants.java */

package com.sun.stylesheet.css.parser;

public interface CSSParserImplTreeConstants
{
  public int JJTSTYLESHEET = 0;
  public int JJTRULE = 1;
  public int JJTSELECTORS = 2;
  public int JJTSIMPLESELECTOR = 3;
  public int JJTSELECTOR = 4;
  public int JJTRELATIONSHIP = 5;
  public int JJTJAVACLASS = 6;
  public int JJTID = 7;
  public int JJTCLASS = 8;
  public int JJTPSEUDOCLASS = 9;
  public int JJTDECLARATION = 10;
  public int JJTTIME = 11;
  public int JJTINTERPOLATION = 12;
  public int JJTDECLEXTRA = 13;
  public int JJTDECLEXTRAS = 14;
  public int JJTPROPERTY = 15;
  public int JJTEXPRESSION = 16;
  public int JJTCOLOR = 17;
  public int JJTCYCLEMETHOD = 18;
  public int JJTLINEARGRADIENT = 19;
  public int JJTFOCUS = 20;
  public int JJTRADIALGRADIENT = 21;
  public int JJTFXOBJECTLITERALBODY = 22;
  public int JJTFXOBJECTLITERAL = 23;
  public int JJTGRADIENT = 24;
  public int JJTNUMBERWITHOPTIONALPERCENT = 25;
  public int JJTPOINT = 26;
  public int JJTSTOP = 27;
  public int JJTCOMPOUNDNAME = 28;
  public int JJTARGUMENT = 29;
  public int JJTARGUMENTLIST = 30;
  public int JJTPARAMS = 31;
  public int JJTIDENTIFIER = 32;


  public String[] jjtNodeName = {
    "Stylesheet",
    "Rule",
    "Selectors",
    "SimpleSelector",
    "Selector",
    "Relationship",
    "JavaClass",
    "Id",
    "Class",
    "PseudoClass",
    "Declaration",
    "Time",
    "Interpolation",
    "DeclExtra",
    "DeclExtras",
    "Property",
    "Expression",
    "Color",
    "CycleMethod",
    "LinearGradient",
    "Focus",
    "RadialGradient",
    "FXObjectLiteralBody",
    "FXObjectLiteral",
    "Gradient",
    "NumberWithOptionalPercent",
    "Point",
    "Stop",
    "CompoundName",
    "Argument",
    "ArgumentList",
    "Params",
    "Identifier",
  };
}
